name: konf
base: core18

version: "1.0.0"

summary: Kubernetes template system for Canonical websites.

description: |
  A command-line tool to generate K8s configs
  from Canonical's webteam
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  konf:
    source: .
    plugin: python

apps:
  konf:
    command: konf.py
    plugs:
      - home
