name: konf
base: core18
version: '0.1'
summary: K8s config generator
description: K8s config generator
grade: devel
confinement: classic

parts:
  konf-src:
    source: .
    plugin: dump
    stage:
      - templates/
    prime:
      - templates/
  konf-python:
    source: .
    plugin: python

apps:
  konf:
    command: konf.py
