name: konf
base: core18

version: git

summary: Kubernetes template system for Canonical websites.

description: |
  A command-line tool to generate K8s configs
  from Canonical's webteam
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  konf-templates:
    source: .
    plugin: dump
    stage:
      - templates/
    prime:
      - templates/
  konf-python:
    source: .
    plugin: python

apps:
  konf:
    command: konf.py
    plugs:
      - home
