---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: jaas-ai
spec:
  selector:
    app: jaas.ai
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: jaas-ai
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: jaas.ai
    spec:
      containers:
        - name: jaas-ai
          image: prod-comms.docker-registry.canonical.com/jaas.ai:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: global-envvars
                optional: true
          env:
            - name: SENTRY_DSN
              value: https://5b54e6946be34749935c4dd2d9d01cb8@sentry.is.canonical.com//7
            - name: SEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api
                  key: google-custom-search-key
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "512Mi"

---
