---

kind: Service
apiVersion: v1  # See https://bit.ly/2KdOtrZ
metadata:
  name: manager-assets-ubuntu-com
spec:
  selector:
    app: manager.assets.ubuntu.com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

---

kind: Deployment
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: manager-assets-ubuntu-com
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: manager.assets.ubuntu.com
    spec:
      containers:
        - name: manager-assets-ubuntu-com
          image: prod-comms.docker-registry.canonical.com/manager.assets.ubuntu.com:${TAG_TO_DEPLOY}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: envvars
                optional: true
            - configMapRef:
                name: proxy-config
                optional: true
          env:
            - name: ASSET_SERVER_URL
              value: https://assets.ubuntu.com/v1/
            - name: ASSET_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: manager-assets-ubuntu-com
                  key: asset_server_token
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: manager-assets-ubuntu-com
                  key: secret_key
          readinessProbe:
            httpGet:
              path: /_status/check
              port: 80
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"

---
