---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ get_site_name() }}
  namespace: {{ data.namespace }}
spec:
  replicas: {{ data.replicas | default(5) }}
  template:
    metadata:
      labels:
        app: {{ domain }}
    spec:
      containers:
        - name: {{ get_site_name() }}
          image: {{ data.image }}:{{ data.tag | default("latest", true) }}

          ports:
            - name: http
              containerPort: {{ data.containerPort | default(80) }}

          env:
            - name: TALISKER_NETWORKS
              value: 10.0.0.0/8

            {%- if data.useProxy != False %}
            - name: HTTP_PROXY
              value: "http://squid.internal:3128/"

            - name: HTTPS_PROXY
              value: "http://squid.internal:3128/"

            - name: NO_PROXY
              value: "ubuntu.com,.ubuntu.com,snapcraft.io,.snapcraft.io,jujucharms.com,.jujucharms.com,maas.io,.maas.io,conjure-up.io,.conjure-up.io,netplan.io,.netplan.io,canonical.com,.canonical.com,launchpad.net,.launchpad.net,linuxcontainers.org,.linuxcontainers.org,cloud-init.io,.cloud-init.io,vanillaframework.io,.vanillaframework.io"
            {%- endif %}

            {%- for env in data.env %}
            - name: {{ env.name }}
              {%- if env.value %}
              value: "{{ env.value }}"
              {%- endif %}

              {%- if env.secretKeyRef %}
              valueFrom:
                secretKeyRef:
                  key: {{ env.secretKeyRef.key }}
                  name: {{ env.secretKeyRef.name }}
              {%- endif %}

              {%- if env.configMapKeyRef %}
              valueFrom:
                configMapKeyRef:
                  key: {{ env.configMapKeyRef.key }}
                  name: {{ env.configMapKeyRef.name }}
              {%- endif %}
            {%- endfor %}

          {%- if data.readinessPath != false %}
          readinessProbe:
            httpGet:
              path: {{ data.readinessPath | default("/_status/check") }}
              port: 80
            periodSeconds: 5
            timeoutSeconds: 3
          {%- endif %}

          resources:
            limits:
              memory: {{ data.memoryLimit | default("256Mi") }}
