---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ getSiteName() }}
  namespace: {{ data.namespace }}
spec:
  replicas: {{ data.replicas | default(5) }}
  template:
    metadata:
      labels:
        app: {{ domain }}
    spec:
      containers:
        - name: {{ getSiteName() }}
          image: {{ data.image }}:{{ data.tag | default("latest", true) }}

          ports:
            - name: http
              containerPort: {{ data.containerPort | default(80) }}

          envFrom:
            {%- if data.useProxy != False %}
            - configMapRef:
                name: proxy-config
                optional: true
            {%- endif %}

          {%- if data.env %}
          env:
            - name: TALISKER_NETWORKS
              value: 10.0.0.0/8

            {%- for env in data.env %}
            - name: {{ env.name }}
              {%- if env.value %}
              value: "{{ env.value }}"
              {%- endif %}

              {%- if env.secretKeyRef %}
              valueFrom:
                secretKeyRef:
                  key: {{ env.secretKeyRef.key }}
                  name: {{ env.secretKeyRef.name }}
              {%- endif %}

              {%- if env.configMapKeyRef %}
              valueFrom:
                configMapKeyRef:
                  key: {{ env.configMapKeyRef.key }}
                  name: {{ env.configMapKeyRef.name }}
              {%- endif %}
            {%- endfor %}
          {%- endif %}

          {%- if data.readinessPath != false %}
          readinessProbe:
            httpGet:
              path: {{ data.readinessPath | default("/_status/check") }}
              port: 80
            periodSeconds: 5
            timeoutSeconds: 3
          {%- endif %}

          resources:
            limits:
              memory: {{ data.memoryLimit | default("256Mi") }}
