kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ name }}
  namespace: {{ data.namespace }}
spec:
  replicas: {{ data.replicas | default(5) }}
  template:
    metadata:
      labels:
        app: {{ domain }}
    spec:
      terminationGracePeriodSeconds: {{ data.terminationGracePeriodSeconds | default(30) }}
      containers:
        - name: {{ name }}
          image: {{ data.container.image }}:{{ data.container.tag | default("latest", true) }}

          {%- if data.lifecycle %}
          lifecycle:
            {%- for lifecycle in data.lifecycle %}
            {%- if lifecycle.preStopCommand %}
            preStop:
              exec:
                command:
                  {%- for command in lifecycle.preStopCommand %}
                  - {{ command }}
                  {%- endfor %}
            {%- endif %}
            {%- endfor %}
          {%- endif %}

          ports:
            - name: http
              containerPort: {{ data.container.port | default(80) }}

          envFrom:
            {%- if data.globalEnvVars != false %}
            - configMapRef:
                name: {{ data.globalEnvVars | default("global-envvars") }}
                optional: true
            {%- endif %}

            {%- if data.useSquid %}
            - configMapRef:
                name: proxy-config
                optional: true
            {%- endif %}

            {%- for env in data.envFrom %}
            {%- if env.configMapRef %}
            - configMapRef:
                name: {{ env.configMapRef.name }}
            {%- endif %}
            {%- endfor %}

          {%- if data.envSecrets %}
          env:
            {%- for env in data.envSecrets %}
            - name: {{ env.name }}
              {%- if env.value %}
              value: "{{ env.value }}"
              {%- endif %}

              {%- if env.secretKeyRef %}
              valueFrom:
                secretKeyRef:
                  key: {{ env.secretKeyRef.key }}
                  name: {{ env.secretKeyRef.name }}
              {%- endif %}

              {%- if env.configMapKeyRef %}
              valueFrom:
                configMapKeyRef:
                  key: {{ env.configMapKeyRef.key }}
                  name: {{ env.configMapKeyRef.name }}
              {%- endif %}
            {%- endfor %}
          {%- endif %}

          {%- if data.readinessProbe != false %}
          readinessProbe:
            httpGet:
              path: {{ data.readinessPath | default("/_status/check") }}
              port: {{ data.port | default(80) }}
            periodSeconds: {{ data.readinessPeriodSeconds | default(5) }}
            successThreshold: {{ data.readinessSuccessThreshold | default(1) }}
            timeoutSeconds: {{ data.readinessTimeoutSeconds | default(3) }}
          {%- endif %}

          resources:
            limits:
              memory: {{ data.memory | default("256Mi") }}
