---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ getSiteName(True) }}
  namespace: {{ data.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {%- if data.nginxConfigurationSnippet %}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{ data.nginxConfigurationSnippet | indent(6) }}
    {%- endif %}

spec:
  {%- if not data.noTls and data.noTls is not defined %}
  tls:
  - secretName: {{ getSiteName(True) }}-tls

    hosts:
      - {{ domain | siteDomain }}
    {%- if (domain | siteDomain | isApexDomain) %}
      - www.{{ domain | siteDomain }}
    {%- endif %}

    {%- for host in data.extraHosts %}
      {%- if host.useParentTLS %}
      - {{ host.domain | siteDomain }}
      {%- if (host.domain | siteDomain | isApexDomain) %}
      - www.{{ host.domain | siteDomain }}
      {%- endif %}
      {%- endif %}
    {% endfor %}
  {%- endif %}

  {%- for host in data.extraHosts %}
  {%- if not host.useParentTLS %}
  - secretName: {{ host.domain | siteDomain | replace(".", "-") }}-tls
    hosts:
      - {{ host.domain | siteDomain }}
      {%- if (host.domain | siteDomain | isApexDomain) %}
      - www.{{ host.domain | siteDomain }}
      {%- endif %}
  {%- endif %}
  {% endfor %}

  rules:
  - host: {{ domain | siteDomain }}
    http: &http_service
      paths:
      - path: /
        backend:
          serviceName: {{ getSiteName() }}
          servicePort: 80

      {%- for route in data.routes %}
      - path: {{ route.path }}
        backend:
          serviceName: {{ getSiteName() ~ route.path | replace("/", "-") }}
          servicePort: 80
      {% endfor %}

  {% if (domain | siteDomain | isApexDomain) %}
  - host: www.{{ domain | siteDomain }}
    http: *http_service
  {%- endif %}

  {% for host in data.extraHosts %}
  - host: {{ host.domain | siteDomain }}
    http: *http_service

  {%- if (host.domain | siteDomain | isApexDomain) %}
  - host: www.{{ host.domain | siteDomain }}
    http: *http_service
  {%- endif %}
  {% endfor %}
