---

kind: Service
apiVersion: v1
metadata:
  name: {{ get_site_name() }}
  namespace: {{ namespace }}
spec:
  selector:
    app: {{ domain }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
