kind: Service
apiVersion: v1
metadata:
  name: {{ name }}
  namespace: {{ data.namespace }}
spec:
  selector:
    app: {{ domain }}
  ports:
    - name: http
      protocol: TCP
      port: {{ data.port | default(80) }}
      targetPort: http
