---

kind: Service
apiVersion: v1
metadata:
  name: {{ getSiteName() }}
  namespace: {{ data.namespace }}
spec:
  selector:
    app: {{ domain }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
