---

kind: Ingress
apiVersion: extensions/v1beta1  # See https://bit.ly/2KdOtrZ
metadata:
  name: manager-staging-assets-ubuntu
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Robots-Tag: noindex";
spec:
  tls:
  - secretName: manager-staging-assets-ubuntu-tls
    hosts:
    - manager.staging.assets.ubuntu
  rules:
  - host: manager.staging.assets.ubuntu
    http:
      paths:
      - path: /
        backend:
          serviceName: manager-assets-ubuntu-com
          servicePort: 80

---
