name: Tests
on: pull_request

jobs:
  test-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # https://github.com/actions/virtual-environments/issues/937
      - name: Temporal fix
        run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build Konf snap
        run: /snap/bin/snapcraft --destructive-mode

      - name: Install konf snap
        run: sudo snap install --dangerous konf_*.snap

      - uses: actions/upload-artifact@v2
        with:
          name: konf-snap
          path: konf_*.snap

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install system dependencies
        run: sudo pip3 install flake8 black

      - name: Lint Python
        run: flake8 . && black --line-length 79 --check .
