name: Tests
on: pull_request

jobs:
  test-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build Konf snap
        run: /snap/bin/snapcraft --destructive-mode

      - name: Install konf snap
        run: sudo snap install --dangerous konf_*.snap

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install system dependencies
        run: sudo pip3 install flake8 black

      - name: Lint Python
        run: flake8 . && black --line-length 79 --check .
